services:
  db:
    image: postgres:16
    container_name: yadro
    environment:
      POSTGRES_DB: yadro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
